### ISSUE TITLE
It doesn't work with python > 3.9 on macos

### ISSUE THREAD

**Issue by QuentinWidlocher** [suborb/philips_android_tv#49]
Idk why, I just know that installing python 3.9 solved it.

Here were my errors for searching purpose.

At first I got

```
ModuleNotFoundError: No module named 'urllib3'
```

After installing `urllib3` I got

```
ModuleNotFoundError: No module named 'cgi'
```

After installing `legacy-cgi` I got

```
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

So if you have the same problem, run this

```
brew install python@3.9
python3.9 -m pip install -r requirements.txt
python3.9 philips.py --host YOUR_IP pair
```

I also needed to hit Shift+Enter to validate my pin.
